// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS6oJFSNy8HUeh_9VzsDAjCzimE-RMob4',
    appId: '1:740154013912:web:c726dd09eef01bccc17fad',
    messagingSenderId: '740154013912',
    projectId: 'ricoode-532f9',
    authDomain: 'ricoode-532f9.firebaseapp.com',
    storageBucket: 'ricoode-532f9.appspot.com',
    measurementId: 'G-141ZQG6C5V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDsZqwUcJzXbzhUsMeApnquOyUYMlpnkwY',
    appId: '1:740154013912:android:bc331adcaf5efd40c17fad',
    messagingSenderId: '740154013912',
    projectId: 'ricoode-532f9',
    storageBucket: 'ricoode-532f9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDn2F4PXDSvvYR1P_m5Ylma8rhF9s6GDu4',
    appId: '1:740154013912:ios:2215b90be2fe6105c17fad',
    messagingSenderId: '740154013912',
    projectId: 'ricoode-532f9',
    storageBucket: 'ricoode-532f9.appspot.com',
    iosBundleId: 'com.example.ricoode',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDn2F4PXDSvvYR1P_m5Ylma8rhF9s6GDu4',
    appId: '1:740154013912:ios:50bb6b06b249109fc17fad',
    messagingSenderId: '740154013912',
    projectId: 'ricoode-532f9',
    storageBucket: 'ricoode-532f9.appspot.com',
    iosBundleId: 'com.example.ricoode.RunnerTests',
  );
}
